---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
- name: release
- name: blobs

outputs:
- name: dev_release

run:
  path: release/ci/tasks/build-dev-release.sh
