---
- type: replace
  path: /releases/-
  value:
    name: bosh-virtualbox-cpi
    version: "41"
    url: https://bosh.io/d/github.com/cppforlife/bosh-virtualbox-cpi-release?v=0.0.13
    sha1: 3aee2200f5d7ee20b149c7303009c3f6088ba559

- type: replace
  path: /resource_pools/name=vms/stemcell?
  value:
    url: https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-xenial-go_agent?v=250.9
    sha1: ec327636a44ff3247ed87729d45d17a90a8fabb4

- path: /resource_pools/name=vms/cloud_properties?
  type: replace
  value:
    cpus: 1
    ephemeral_disk: 16384
    memory: 2048

- path: /cloud_provider/template?
  type: replace
  value:
    name: virtualbox_cpi
    release: bosh-virtualbox-cpi

- type: replace
  path: /networks
  value:
  - name: private
    type: manual
    subnets:
    - range: ((internal_cidr))
      gateway: ((internal_gw))
      static: [((internal_ip))]
      dns: [8.8.8.8]
      cloud_properties:
        name: ((network_name))


- type: remove
  path: /instance_groups/name=jumpbox/networks/name=public
