---
- type: replace
  path: /releases/-
  value:
    name: bosh-virtualbox-cpi
    version: "41"
    url: https://bosh.io/d/github.com/cppforlife/bosh-warden-cpi-release?v=41
    sha1: b751ea458fc54f3e9f8af29ff7fa25bcd1f31f4c

- type: replace
  path: /resource_pools/name=vms/stemcell?
  value:
    url: https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-xenial-go_agent?v=250.9
    sha1: d1f77ba0e65920ebf45f9c80dc0187b107b739a0

- path: /resource_pools/name=vms/cloud_properties?
  type: replace
  value:
    cpus: 1
    ephemeral_disk: 16384
    memory: 2048

- path: /cloud_provider/template?
  type: replace
  value:
    name: virtualbox_cpi
    release: bosh-virtualbox-cpi
