---
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=credhub?
  value:
    name: credhub
    release: jumpbox-utils
    properties: {}

- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=set-path/properties?/jumpbox/clis/-
  value:
    script: /var/vcap/packages/credhub/bin/credhub
    version_option: --version
