---
- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=jq?
  value:
    name: jq
    release: jumpbox-utils
    properties: {}

- type: replace
  path: /instance_groups/name=jumpbox/jobs/name=set-path/properties?/jumpbox/clis/-
  value:
    script: /var/vcap/packages/jq/bin/jq
    version_option: --version
